version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
      AIRFLOW__UID: "1000"  # UID ajustado
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./validation:/opt/airflow/validation
      - ./export:/opt/airflow/export
      - ./output:/opt/airflow/output
      - ./backups:/opt/airflow/backups
      - ./plugins:/opt/airflow/plugins
    command: >
      bash -c " airflow db init && airflow users create --username airflow --password airflow --firstname Edivan --lastname Junior --role Admin --email ejgjedivan@gmail.com && airflow webserver"

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
      AIRFLOW__UID: "1000"  # UID ajustado
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./validation:/opt/airflow/validation
      - ./export:/opt/airflow/export
      - ./output:/opt/airflow/output
      - ./backups:/opt/airflow/backups
      - ./plugins:/opt/airflow/plugins
    command: >
      bash -c " airflow db init && airflow scheduler"

volumes:
  postgres_data:

